### ISSUE TITLE
Root directory creation permissions (creation info ) ignored 

### ISSUE THREAD

**Issue by qxmips** [cloudposse/terraform-aws-efs#100]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
creation info does not apply and shows as empty under "Root directory creation permissions" in AWS console.

## Expected Behavior
creation info should be populated during creation"

## Steps to Reproduce
```
module "efs" {
  source  = "cloudposse/efs/aws"
  version = "0.32.2"
  region  = var.region
  vpc_id  = module.vpc.vpc_id
  subnets = module.vpc.public_subnets
    "input" = {
      posix_user = {
        gid            = "50000"
        uid            = "50000"
        secondary_gids = 0
      }
      creation_info = {
        gid         = 0
        uid         = 0
        permissions = 0755
      }
    }
     "output" = {
      posix_user = {
        gid            = "50000"
        uid            = "50000"
        secondary_gids = "1001"
      }
      creation_info = {
        gid         = "0"
        uid         = "0"
        permissions = "0755"
      }
    }
    "logs" = {
      posix_user = {
        gid            = "0"
        uid            = "0"
        secondary_gids = "1001"
      }
      creation_info = {
        gid         = "0"
        uid         = "0"
        permissions = "0755"
      }
    }

  }
```

## Screenshots
![image](https://user-images.githubusercontent.com/13249609/143796578-56f95fd9-23f1-464c-a618-4f8e14804f9f.png)

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.13.1
+ provider registry.terraform.io/hashicorp/aws v3.67.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

**Comment by dkossako** [comment]
I reach today same issue, here is the PR: https://github.com/cloudposse/terraform-aws-efs/pull/101/files
