### ISSUE TITLE
Malformed LifecyclePolicy block when both transition parameters are used

### ISSUE THREAD

**Issue by kevouellet** [cloudposse/terraform-aws-efs#103]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
If both `transition_to_ia` and `transition_to_primary_storage_class` are used in the module, the following error is returned by Terraform:

```
Error: error updating EFS file system (fs-***) lifecycle configuration: BadRequest: One or more LifecyclePolicy objects specified are malformed.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "***"
│   },
│   ErrorCode: "BadRequest",
│   Message_: "One or more LifecyclePolicy objects specified are malformed."
│ }
│ 
│   with aws_efs_file_system.default[0],
│   on main.tf line 18, in resource "aws_efs_file_system" "default":
│   18: resource "aws_efs_file_system" "default" {
```

This happens because the module inserts both `transition_to_ia` and `transition_to_primary_storage_class` in one `lifecycle_policy` block, and Terraform expects a distinct `lifecycle_policy` block for each parameter.

**Comment by maartenschalekamp** [comment]
Ran into this issue as well today.

**Comment by nitrocode** [comment]
This has been fixed in https://github.com/cloudposse/terraform-aws-efs/releases/tag/0.32.6

**Comment by maartenschalekamp** [comment]
thank you!
