### ISSUE TITLE
Secondary CIDRS not getting populated

### ISSUE THREAD

**Issue by widdix123** [cloudposse/terraform-aws-efs#107]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
The secondary cidrs are not getting created in the efs_access_points. All Access points are having null secondary cidrs

## Expected Behavior
When secondary cidrs are mentioned, access points created by terraform should have those

## Steps to Reproduce
Run the terraform example and see if access points created have secondary cidrs. As per the current code it will be null for all

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

**Comment by widdix123** [comment]
I know how to get this fix, is there a way in which i could create the PR for the same ?

**Comment by nitrocode** [comment]
@widdix123 yes please feel free to submit a PR to close the issue

**Comment by widdix123** [comment]
@nitrocode  - I am not able to create a PR for the same 

the problem is EFS access points, secondary gids dont work for posix users 

the fix is below

```
  secondary_gids = {
    for k, v in var.access_points :
    k => lookup(local.posix_users[k], "secondary_gids", null)
}
```

**Comment by nitrocode** [comment]
@widdix123 I'm having trouble seeing how this is an issue. Can you show the hcl youre using and its `terraform plan` output?

This is the module code for the secondary gids

https://github.com/cloudposse/terraform-aws-efs/blob/7e5015fc7e96b2a74f9946940e973b2413e68789/main.tf#L8-L15

https://github.com/cloudposse/terraform-aws-efs/blob/7e5015fc7e96b2a74f9946940e973b2413e68789/main.tf#L51-L64

**Comment by widdix123** [comment]
@nitrocode  - line 14 has missing  `[k]` in `local.posix_users`

```
  # module.efs.aws_efs_access_point.default["data"] will be created
  + resource "aws_efs_access_point" "default" {
      + arn             = (known after apply)
      + file_system_arn = (known after apply)
      + file_system_id  = (known after apply)
      + id              = (known after apply)
      + owner_id        = (known after apply)
      + tags            = {
          + "Name" = "data"
        }
      + tags_all        = {
          + "Name" = "data"
        }

      + posix_user {
          + gid = 1001
          + uid = 5000
        }

      + root_directory {
          + path = "/data"

          + creation_info {
              + owner_gid   = 1001
              + owner_uid   = 5000
              + permissions = "0755"
            }
        }
    }
```

After the suggested changes it looks like below
```
  # module.efs.aws_efs_access_point.default["data"] will be created
  + resource "aws_efs_access_point" "default" {
      + arn             = (known after apply)
      + file_system_arn = (known after apply)
      + file_system_id  = (known after apply)
      + id              = (known after apply)
      + owner_id        = (known after apply)
      + tags            = {
          + "Name" = "data"
        }
      + tags_all        = {
          + "Name" = "data"
        }

      + posix_user {
          + gid            = 1001
          + secondary_gids = [
              + 1002,
              + 1003,
            ]
          + uid            = 5000
        }

      + root_directory {
          + path = "/data"

          + creation_info {
              + owner_gid   = 1001
              + owner_uid   = 5000
              + permissions = "0755"
            }
        }
    }
```

**Comment by nitrocode** [comment]
This has been fixed in https://github.com/cloudposse/terraform-aws-efs/releases/tag/0.32.6

**Comment by widdix123** [comment]
@nitrocode  - Cool my fix did make sense
