### ISSUE TITLE
throughput_mode elastic is not supported

### ISSUE THREAD

**Issue by Mayank-Sinha-Infrrd** [cloudposse/terraform-aws-efs#116]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
throughput_mode supports only provisioned and bursting

## Expected Behavior
throughput_mode supports only provisioned and bursting , should be supporting elastic as well

## Steps to Reproduce

module "efs" {
  source  = "cloudposse/efs/aws"
  version = "0.31.1" 
  throughput_mode= "provisioned/bursting/elastic"
}

When we do a terraform plan. It shows that the elastic mode is not supported yet.

## Screenshots
*************************************************************************************
Terraform plan gives: -
Acquiring state lock. This may take a few moments...
╷
│ Error: expected throughput_mode to be one of [bursting provisioned], got elastic
│ 
│   with module.block_efs.module.efs.aws_efs_file_system.default[0],
│   on .terraform/modules/block_efs.efs/main.tf line 13, in resource "aws_efs_file_system" "default":
│   13:   throughput_mode                 = var.throughput_mode
│ 
╵
Releasing state lock. This may take a few moments...
******************************************************************************************

Anything that will help us triage the bug will help. Here are some ideas:
 - OS:  Linux
 - Version : 0.31.1

**Comment by ByJacob** [comment]
There are no restrictions on the throughput mode in the code.
Upgrade AWS provider - https://developer.hashicorp.com/terraform/tutorials/configuration-language/provider-versioning#upgrade-the-aws-provider-version

**Comment by Mayank-Sinha-Infrrd** [comment]
Hey  @ByJacob , Thanks for pointing it out. 
I upgraded the version : terraform init -upgrade .

I was able to create efs with throughput mode as elastic post that.
Thanks again .
