### ISSUE TITLE
Module Upgrade New – Announcing Amazon EFS Elastic Throughput

### ISSUE THREAD

**Issue by Alexvianet** [cloudposse/terraform-aws-efs#119]
Please upgrade the module to enable New Amazon EFS Elastic Throughput
https://aws.amazon.com/blogs/aws/new-announcing-amazon-efs-elastic-throughput/

On the latest module version i got:
│ Error: expected throughput_mode to be one of [bursting provisioned], got elastic
│ 
│   with module.efs.aws_efs_file_system.default[0],
│   on .terraform/modules/efs/main.tf line 27, in resource "aws_efs_file_system" "default":
│   27:   throughput_mode                 = var.throughput_mode

**Comment by gartemiev** [comment]
@Alexvianet , just upgrade your AWS provider version to the latest one and it will work out - there are no restrictions in module itself regarding this.
