### ISSUE TITLE
Support transition_to_archive lifecycle policy

### ISSUE THREAD

**Issue by yaronya** [cloudposse/terraform-aws-efs#132]
### Describe the Feature

AWS recently added a [new storage class to EFS called Archive](https://aws.amazon.com/blogs/aws/optimize-your-storage-costs-for-rarely-accessed-files-with-amazon-efs-archive/)
AWS Terraform provider will soon have a release that adds support to it (see [PR](https://github.com/hashicorp/terraform-provider-aws/pull/35096))

### Expected Behavior

Similar to the existing `transition_to_ia` input, add a new `transition_to_archive` input

### Use Case

The new Archive EFS storage class has potential savings of about 50% of the unused data

### Describe Ideal Solution

Add a new `transition_to_archive` input that supports the relevant values

**Comment by sufyan-demicon** [comment]
Hello @osterman 

Can you please add this variable `transition_to_archive`.

this is a blocker for us to keep using your EFS module. 

Thank you.
