### ISSUE TITLE
Cannot parse as float error

### ISSUE THREAD

**Issue by stelang** [cloudposse/terraform-aws-efs#18]
Getting below error when I use your module. I used the example provided in the readme in my main.tf.
Is there a work around for this?
`Error: module.efs.aws_efs_file_system.default: provisioned_throughput_in_mibps: cannot parse '' as float: strconv.ParseFloat: parsing "": invalid syntax`

**Comment by aknysh** [comment]
Addressed in https://github.com/cloudposse/terraform-aws-efs/pull/19
