### ISSUE TITLE
Add lifecycle policy

### ISSUE THREAD

**Issue by ivan-sphere** [cloudposse/terraform-aws-efs#31]
Amazon recently released lifecycle policy for EFS, are there any plans to support this feature in your module?
https://aws.amazon.com/efs/features/infrequent-access/

**Comment by daHaimi** [comment]
+1

**Comment by arischow** [comment]
Really need it and made a #40 🤗

**Comment by js-timbirkett** [comment]
@ivan-sphere - I think PR #40 fixes this. Can this be closed now?

**Comment by Nuru** [comment]
Closing as fixed by #40. Please open a new feature request if one is still needed.
