### ISSUE TITLE
Do not use in-line security group rules

### ISSUE THREAD

**Issue by pnickerson-cashstar** [cloudposse/terraform-aws-efs#33]
Terraform has two resources that can define security group rules: In-line inside `aws_security_group`, or as attachments with `aws_security_group_rule`. Terraform says [here](https://www.terraform.io/docs/providers/aws/r/security_group.html) that you should not use both in-line and attached rules:

> At this time you cannot use a Security Group with in-line rules in conjunction with any Security Group Rule resources. Doing so will cause a conflict of rule settings and will overwrite rules.

AWS [supports](https://docs.aws.amazon.com/efs/latest/ug/manage-fs-access-vpc-peering.html) mounting EFS file systems across VPC peering connections. Normally, once a VPC peering connection is established, you are able to reference security groups in the other VPC inside your security group rules. However, if that peering connection is inter-region (the VPC's are in different regions), then AWS [says](https://docs.aws.amazon.com/vpc/latest/peering/vpc-peering-security-groups.html) you cannot reference SG ID's:

> You cannot reference the security group of a peer VPC that's in a different region. Instead, use the CIDR block of the peer VPC.

So, when using the `cloudposse/terraform-aws-efs` module, the `security_groups` input cannot be used with inter-region VPC peering. This should be OK, as the module now outputs the created security group's ID, and so I can add a custom ingress rule later.

Except that doesn't work, since the module is using in-line rules inside `aws_security_group`, instead of attached rules with `aws_security_group_rule`.

Can you switch to using `aws_security_group_rule`, please?

**Comment by aknysh** [comment]
thanks @pnickerson-cashstar  for reporting the issue.
We will look into that, but to speedup the process, if you know how to implement it, PRs are always welcome :)

**Comment by pnickerson-cashstar** [comment]
Thank you for planning to look into this.

I'm afraid I'm not familiar enough with Terraform's count and index things to be confident in submitting a PR. But I think what you'd want to do is remove the `ingress` and `egress` blocks from the `aws_security_group` resource, and then add these two resources:

```
resource "aws_security_group_rule" "allow_nfs_in" {
  count                    = var.enabled ? length(var.security_groups) : 0
  type                     = "ingress"
  from_port                = "2049" # NFS
  to_port                  = "2049"
  protocol                 = "tcp"
  source_security_group_id = var.security_groups[count.index]
  security_group_id        = aws_security_group.default[0].id
}

resource "aws_security_group_rule" "allow_all_out" {
  count             = var.enabled ? 1 : 0
  type              = "egress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  cidr_blocks       = ["0.0.0.0/0"]
  security_group_id = aws_security_group.default[count.index].id
}
```

But I'm really not sure if that's the right way to do the counts. It does seem to work for my specific situation.
