### ISSUE TITLE
make readme removes all inputs and outputs

### ISSUE THREAD

**Issue by stefansedich** [cloudposse/terraform-aws-efs#36]
I am trying to get together a PR for kms_key_id support and as soon as I run `make readme` it works but it removes all of the inputs and outputs from the resultant README.md, is there something special I need to be doing?

**Comment by osterman** [comment]
The `README.md` is generated from the `README.yaml`. Make all your changes to the `README.yaml`, then rebuild. The outputs are generated using `terraform-docs`. Just make sure you add a proper `description` field to all outputs and variables.

Please rebuild the `README.md` by running the following commands:
```
make init
make readme/deps
make readme
```

There might be a lot of changes in the `README.md` as a result. That's okay! 

Sorry for the inconvenience!

**Comment by stefansedich** [comment]
@osterman that still removes the entire inputs/outputs tables, there is nothing about inputs/outputs in the existing README.yaml should there be?

**Comment by stefansedich** [comment]
@osterman I opened the PR anyway can discuss what is happening over there.

**Comment by osterman** [comment]
Someone else has reported this issue as well. Not sure when it started happening. I will look into it.
