### ISSUE TITLE
Getting `expected ip_address to contain a valid IPv4 address` error with AWS provider >= 2.65.0

### ISSUE THREAD

**Issue by zephinzer** [cloudposse/terraform-aws-efs#44]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
The AWS provider 2.65.0 introduces additional validation for the `ip_address` property used in the `aws_efs_mount_target` resource, previously a blank string will leave it to AWS, but it's now returning an error:

```
Error: expected ip_address to contain a valid IPv4 address, got: 

  on .terraform/modules/efs/terraform-aws-efs-0.16.0/main.tf line 34, in resource "aws_efs_mount_target" "default":
  34: resource "aws_efs_mount_target" "default" {
```

See https://github.com/terraform-providers/terraform-provider-aws/issues/13626 for more info

## Expected Behavior
Not specifying the `mount_target_ip_address` should work as before.

## Steps to Reproduce
1. Attempt to provision a new EFS without setting the `mount_target_ip_address` variable

## Screenshots
NA

## Environment (please complete the following information):

```
# terraform version 
> Terraform v0.12.26

# terragrunt --version
> terragrunt version v0.23.7

# terragrunt version
> Terraform v0.12.26
> + provider.aws v2.67.0
> + provider.local v1.4.0
> + provider.null v2.1.2
```

## Additional Context
The solution will be to set the default for `mount_target_ip_address` to `null` instead of an empty string, this seems backward compatible too-

**Comment by abdennour** [comment]
same issue as well : 

```
Error: expected ip_address to contain a valid IPv4 address, got: 

  on .terraform/modules/external_storage.efs/main.tf line 34, in resource "aws_efs_mount_target" "default":
  34: resource "aws_efs_mount_target" "default" {
```

**Comment by abdennour** [comment]
I've open new PR #49 which must fix the issue.
