### ISSUE TITLE
Upgrade module source version for label and route53 for 0.13 version compatibility

### ISSUE THREAD

**Issue by ohayak** [cloudposse/terraform-aws-efs#52]
in order to work with terraform 0.13 these sources need to be updated:

  source      = "git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.16.0"
  source      = "git::https://github.com/cloudposse/terraform-aws-route53-cluster-hostname.git?ref=tags/0.3.0"

**Comment by jurgenweber** [comment]
I would also argue that you should increase the version constraint for the AWS provider to v3 which is the TF13 compatible version of the provider:

   aws   = "=> 2.0"

**Comment by jurgenweber** [comment]
https://github.com/cloudposse/terraform-aws-route53-cluster-hostname/issues/23
