### ISSUE TITLE
Security group name, formatting does not work

### ISSUE THREAD

**Issue by charlie4gfk** [cloudposse/terraform-aws-efs#61]
Securitu group, created by this module has name "-efs" and `module.this.id` part is basically ignored. The part which configures SG name:
https://github.com/cloudposse/terraform-aws-efs/blob/5994e4b684460e005db2f02691a0ab96d913735f/main.tf#L56

I guess it could be also TF's bug. I am using:
```
Terraform v0.12.29
+ provider.aws v3.4.0
+ provider.local v2.0.0
+ provider.null v3.0.0
+ provider.template v2.2.0
```

**Comment by michalschott** [comment]
Looks like it happens if you leave `name` empty.

**Comment by Nuru** [comment]
You must set at least one of:
- namespace
- environment
- stage
- name

to get useful names and tags with any of the Cloud Posse Terraform modules. See [terraform-null-label](https://github.com/cloudposse/terraform-null-label) for more about how we label resources.
