### ISSUE TITLE
Access Points Dont Appear to work

### ISSUE THREAD

**Issue by jseiser** [cloudposse/terraform-aws-efs#81]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
When attempting to pass in access points, you get various type errors

## Expected Behavior
Access Points are created

## Steps to Reproduce
```
  on main.tf line 17, in module "efs":
  17:   access_points = {
  18:     jenkins = {
  19:       posix_user = {
  20:         uid = 1000
  21:         gid = 1000
  22:         secondary_gids = null
  23:       }
  24:       root_directory = {
  25:         path = "/jenkins"
  26:         creation_info = {
  27:           owner_gid = 1000
  28:           owner_uid = 1000
  29:           permissions = 777
  30:         }
  31:       }
  32:     }
  33:   }
```

The given value is not suitable for child module variable "access_points"
defined at .terraform/modules/efs/variables.tf:12,1-25: element "jenkins":
element "root_directory": all map elements must have the same type.
## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Terraform 0.14.6

**Comment by Nuru** [comment]
This is not a bug, this is a failure of documentation that should have been part of the feature implementation in #58 (cc: @Gowiem @aknysh ). It would be great for someone to add good documentation of this feature in the README.yaml.

If you look at the implementation:
https://github.com/cloudposse/terraform-aws-efs/blob/2652b410be3ff1ba77ffbad9c3eeaaba6f0323a9/main.tf#L36-L58

you will see that the input format is different than you expected/provided. I believe what you wanted is

```hcl
access_points = {
  jenkins = {
    posix_user = {
      uid            = 1000
      gid            = 1000
      secondary_gids = null
    },
    creation_info = {
      owner_gid   = 1000
      owner_uid   = 1000
      permissions = 777
    }
  }
}

```

If that does not work, please provide some more details and we can re-open this issue.

**Comment by fangj99** [comment]
It seems we have to remove prefix "owner" in creation_info or tf will give our error

```
Error: Invalid index

  on ../../../module/efs/main.tf line 52, in resource "aws_efs_access_point" "default":
  52:       owner_uid   = var.access_points[each.key]["creation_info"]["uid"]
    |----------------
    | each.key is "prometheus"
    | var.access_points is map of map of map of number with 4 elements

The given key does not identify an element in this collection value.
```

It will work if we changed to following code: 

```
access_points = {
  prometheus = {
    posix_user = {
      uid            = 1000
      gid            = 1000
      secondary_gids = null
    },
    creation_info = {
      gid   = 1000
      uid   = 1000
      permissions = 777
    }
  }
}
```
