### ISSUE TITLE
An argument named "transition_to_primary_storage_class" is not expected

### ISSUE THREAD

**Issue by chris-str-cst** [cloudposse/terraform-aws-efs#96]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
After upgrading to the latest version `0.32.0` I'm getting the following error when running `apply`
```bash 
│ Error: Unsupported argument
│
│   on main.tf line 33, in resource "aws_efs_file_system" "default":
│   33:       transition_to_primary_storage_class = try(var.transition_to_primary_storage_class[0], null)
│
│ An argument named "transition_to_primary_storage_class" is not expected
│ here.
╵
ERRO[0005] 1 error occurred:
	* exit status 1
``` 
Parameters:
```bash
... 
allowed_security_group_ids = [dependency.sg-efs.outputs.id]
security_group_enabled = false
efs_backup_policy_enabled = true
```

## Expected Behavior
No Errors on applying. 

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: OSX
 - Version: 11.6

## Additional Context
```bash
Initializing modules...
Downloading cloudposse/route53-cluster-hostname/aws 0.12.2 for dns...
- dns in .terraform/modules/dns
Downloading cloudposse/label/null 0.25.0 for dns.this...
- dns.this in .terraform/modules/dns.this
Downloading cloudposse/security-group/aws 0.4.2 for security_group...
- security_group in .terraform/modules/security_group
Downloading cloudposse/label/null 0.25.0 for security_group.this...
- security_group.this in .terraform/modules/security_group.this
Downloading cloudposse/label/null 0.25.0 for this...
- this in .terraform/modules/this

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Installing hashicorp/aws v3.49.0...
- Installed hashicorp/aws v3.49.0 (signed by HashiCorp)

Terraform has been successfully initialized!
```

**Comment by nitrocode** [comment]
@chris-str-cst are you supplying `transition_to_primary_storage_class` to the module ? What are your full inputs ?

**Comment by nitrocode** [comment]
I'm going to keep this open until the provider gets bumped in this module to prevent this from happening again.

Thanks for reporting this @chris-str-cst

**Comment by nitrocode** [comment]
@chris-str-cst we've bumped the provider to a higher version to prevent this. Please use module version 0.32.1 and it should resolve this issue.

**Comment by chris-str-cst** [comment]
@nitrocode Thank you very much!
